[tool.poetry]
name = "django-q"
version = "1.3.4"
description = "A multiprocessing distributed task queue for Django"
authors = ["Ilan Steemers <koed00@gmail.com>"]
license = "MIT"
readme = 'README.rst'

repository = "https://github.com/koed00/django-q"
homepage = "https://django-q.readthedocs.org"
documentation = "https://django-q.readthedocs.org"

keywords = ["django", "distributed", "multiprocessing", "queue","scheduler"]

classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Environment :: Web Environment',
        'Framework :: Django',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Operating System :: POSIX',
        'Operating System :: MacOS',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Topic :: Internet :: WWW/HTTP',
        'Topic :: System :: Distributed Computing',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ]
include=['CHANGELOG.md']

[tool.poetry.plugins."djangoq.errorreporters"]
"rollbar" = "django_q_rollbar:Rollbar"
"sentry" = "django_q_sentry:Sentry"


[tool.poetry.dependencies]
python = ">=3.6"
django = ">=2.2"
blessed = "^1.17.6"
arrow = "^0.15.6"

django-q-rollbar= { version = "^0.1", optional = true }
django-q-sentry = { version = "^0.1", optional = true }
django-picklefield = "^3.0.1"
hiredis = {version = "^1.0.1", optional = true}
redis = {version = "^3.5.3", optional = true}
psutil = {version = "^5.7.0", optional = true}
django-redis = {version = "^4.12.1", optional = true}
iron-mq = {version = "^0.9", optional = true}
boto3 = {version = "^1.14.12", optional = true}
pymongo = {version = "^3.10.1", optional = true}
croniter = {version = "^0.3.34", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^5.4.2"
pytest-django = "^3.9.0"

[tool.poetry.extras]
rollbar = ["django-q-rollbar"]
sentry = ["django-q-sentry "]
requires = ["poetry>=0.12"]
build-backend = ["poetry.masonry.api"]

